### ISSUE TITLE
存在しないアイテムコードのチェック漏れ？

### ISSUE THREAD

**Issue by t-nkgw** [gghatano/pwscup2018eval#5]
check.bash実行時、アイテムを元データに存在しないものと合わせて一般化してもエラーにならないようです  
- 入力例
    - T.csv  
`13047,2010/12/1,84879,1.69,32`  

    - A.csv  
`99999,[2010/12/01;2011/12/01],{84879;XXXXX},[1.69;1.69],[32;32]`

**Comment by gghatano** [comment]
ご指摘ありがとうございます。

確認いたします。

**Comment by gghatano** [comment]
修正いたしました
一般化したアイテムの中に、存在しないアイテムコードがあると、以下のように表示されます
```
$ bash check.bash
line 2: cell 3: invalid STOCK: 13047,2010/12/1,{XXX;22745},2.1,6
```
ご指摘、ありがとうございました
